<Project>
	<PropertyGroup>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
		<ImplicitUsings>enable</ImplicitUsings>
		<AnalysisMode>AllEnabledByDefault</AnalysisMode>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>
</Project>